"""add product images relation

Revision ID: 86390dc4c9e0
Revises: c2ef87b5017f
Create Date: 2025-05-23 05:21:23.666154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86390dc4c9e0'
down_revision = 'c2ef87b5017f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.INTEGER(), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
