"""Agrego campos que faltaban como phone

Revision ID: c159d6cb7c2c
Revises: 54f1e2a4e2e0
Create Date: 2025-05-27 02:50:01.242070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c159d6cb7c2c'
down_revision = '54f1e2a4e2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product_image', schema=None) as batch_op:
        batch_op.drop_column('position')

    # ### end Alembic commands ###
